M48
; DRILL file KiCad 10.0.4 date 2026-06-23T19:25:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-23T19:25:31-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X132.585Y-86.01
X132.585Y-91.79
T2
X166.013Y-77.822
X169.013Y-77.822
M30
